import './globals.css';
import type { Metadata } from 'next';
import { roboto, exo2 } from '@/app/fonts';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface LayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
    return (
        <html lang='en' className={`${exo2.variable} ${roboto.variable}`}>
            <body className='font-exo2'>
                <header>
                    <ul>
                        <li>
                            <a href='/'>Home</a>
                        </li>
                        <li>
                            <a href='/savings'>Savings</a>
                        </li>
                        <li>
                            <a href='/about'>About</a>
                        </li>
                    </ul>
                </header>
                <main className='flex min-h-screen flex-col items-center justify-between p-24'>
                    {children}
                </main>
                <footer>[Footer]</footer>
            </body>
        </html>
    );
}
